title: Vish Here!!
description: > # this means to ignore newlines until "baseurl:"
 We give you a completely new thaught that how a love story can be perfecty 
 "promulgated uniquely"
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://vsh12.github.io/vish/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "" #if your site has a twitter account, enter it here

# Author Settings
author: David Freeman # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: artemsheludko # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
